steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk:$COMMIT_SHA'
      - '-f'
      - 'deploy/app/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - services
      - update
      - docu-talk
      - '--image'
      - 'europe-west1-docker.pkg.dev/ai-apps-445910/docu-talk/docu-talk:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'